# Generated by Django 5.2 on 2025-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ocekavane',
            field=models.DateField(blank=True, null=True, verbose_name='Očekávaný termín'),
        ),
    ]
